volumes:
  voting_app_data:
    name: voting_app_data

services:
  postgres_db:
    container_name: voting_app_db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: voting_app
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "voting_app"]
      interval: 10s
      retries: 3
    volumes:
      - voting_app_data:/var/lib/postgresql/data
    restart: unless-stopped

  voting_app_backend:
    container_name: voting_app_backend
    build: ./backend 
    image: voting_app_backend
    environment:
      DATABASE_URL: postgresql://admin:secret@voting_app_db/voting_app 
    depends_on:
      postgres_db:
        condition: service_healthy
    entrypoint: ["uvicorn"]
    command: ["app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    
  voting_app_frontend:
    container_name: voting_app_frontend 
    build: ./frontend 
    image: voting_app_frontend
    environment:
      REACT_APP_API_BASE_URL: https://localhost
    depends_on:
      postgres_db:
        condition: service_healthy
    ports:
      - 3000:3000
    entrypoint: ["npm"]
    command: ["start"]

  voting_app_proxy:
    container_name: voting_app_reverse_proxy
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - voting_app_backend
      - voting_app_frontend


